# Generated by Django 4.2.25 on 2025-10-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_uuid_field_alter_user_id'),
    ]

    operations = [
        # Skip removing uuid_field if it doesn't exist
        migrations.RunSQL(
            sql="SELECT 1;",
            reverse_sql="SELECT 1;"
        ),
    ]
