# Generated by Django 4.2.25 on 2025-10-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_convert_user_id_to_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uuid_field',
        ),
    ]
