# Generated by Django 4.2.25 on 2025-10-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('cod', 'Cash on Delivery')], default='stripe', max_length=20),
        ),
    ]
