# Generated by Django 4.2.25 on 2025-10-17 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_order_guest_email_order_guest_name_order_guest_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carrier', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_delivery_days', models.PositiveIntegerField(default=3)),
                ('max_delivery_days', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='e.g., Home, Office, etc.', max_length=50)),
                ('recipient_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=255)),
                ('apartment', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shipping Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rma_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('reason', models.CharField(choices=[('defective', 'Defective/Damaged'), ('wrong_item', 'Wrong Item Sent'), ('not_as_described', 'Not As Described'), ('changed_mind', 'Changed Mind'), ('size_issue', 'Size/Fit Issue'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('received', 'Item Received'), ('refunded', 'Refunded'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('restocking_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_method', models.CharField(default='original_payment', max_length=50)),
                ('refund_transaction_id', models.CharField(blank=True, max_length=100)),
                ('vendor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('items', models.ManyToManyField(related_name='return_requests', to='orders.orderitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.order')),
                ('vendor_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.vendororder')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCancellation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('customer_request', 'Customer Request'), ('out_of_stock', 'Out of Stock'), ('payment_failed', 'Payment Failed'), ('fraud', 'Suspected Fraud'), ('other', 'Other')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_processed', models.BooleanField(default=False)),
                ('refund_transaction_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cancellations', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='orders.order')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
