# Generated by Django 4.2.25 on 2025-10-15 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_id_alter_inventorytransaction_id_and_more'),
    ]

    operations = [
    ]
